{% set name = "typesystem" %}
{% set version = "0.2.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 608cb3b70116e6930ee89f779598a9e51d381b672e0f5e0cc6caf5d1300157bc

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - typesystem
    - typesystem.tokenize

about:
  home: https://github.com/encode/typesystem
  license: BSD
  license_family: BSD
  license_file: LICENSE.md
  summary: A type system library for Python
  doc_url: https://pypi.org/project/typesystem
  dev_url: https://github.com/encode/typesystem

extra:
  recipe-maintainers:
    - k-dominik
