{% set name = "typesystem" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cc3f03d101fadbb60356993ce600fdfbf4bbce90ce5cb444766962be33f53ce1

build:
  number: 1
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - typesystem
    - typesystem.tokenize

about:
  home: https://github.com/encode/typesystem
  license: BSD
  license_family: BSD
  license_file: LICENSE.md
  summary: A type system library for Python
  doc_url: https://pypi.org/project/typesystem
  dev_url: https://github.com/encode/typesystem

extra:
  recipe-maintainers:
    - k-dominik
