{% set name = "typesystem" %}
{% set version = "0.2.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aa01ac52370a7e5996960c8a899da0f939753bc49d405e92dea5cb1f6bc3700a

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - typesystem
    - typesystem.tokenize

about:
  home: https://github.com/encode/typesystem
  license: BSD
  license_family: BSD
  license_file: LICENSE.md
  summary: A type system library for Python
  doc_url: https://pypi.org/project/typesystem
  dev_url: https://github.com/encode/typesystem

extra:
  recipe-maintainers:
    - k-dominik
