travis:
  secure:
    BINSTAR_TOKEN: jBY1lM4Rq81mhmu8FP/Ca+nVGcxdPRKVN2FKYj5PtbK6sm8upfC9KjWMD+C0oNOmu1Vs07tgzHxO+YLUFYua7TNv0SB5AjV5rvVl8RDIkai6ZbwKjwaFEACaB/eJK0TrTzoJBoO84CykU1e5MFa2s3p/rKCCUgjBO78I6I5RxsG+eAk6v11s2y/uKrs5fK9Tg0dzRhPNNEydUSKTM6UmcNpl4a50P3oKmxSepo78L0rR1fJtw3+9YbWF+PGKgDxhr2bGwqMaflrqr2FYC9O7MqGvhFoK+N0cQGMFEX+ZhD0G4poDPNc1RU5rFAMRB64m5qPB20R8XDyB1LMmKHtmlC1ZwPLI6/wTM3SMeq8el8KxRxRQsWQghLG9wLWUUsSdPJbbeavku7OKbUHlfI1+GmkbZVZQ8eg9z5p19uaqLRGAXj48Yc/GB4Q4XOSNF1chvmCMKrnKtF9nhHc04etJIjicD3xU/SipRx6bSedLyCQxVAIvoNiWDOiizT9CMhaGLeLv3LYKvIl5PjMzKR77PnUcYXjxOX8Hg0Ev+HvgVNJWhbJdXBpccH9Hg61+IaNOCGillEQCr87OP1KVX+n3ogpybI7MHUrcOghx5aXsaizT7JkZdheJKD0NUzn4qtmMOG1VNrJES3f+Z+o0j/QQZhkh+vNC0vvtK89owiB3mOg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
